test_mode: False
machine: "cluster"
device: "cuda"
skip_run_init: False
explicit_run_enumeration: True
skip_saving_and_loading: True
run_num: 19
anomaly_detection: False
mode: gan # 'gan' or 'regression' or 'diagnostic'
gan_loss: standard #wasserstein # standard #distance
train_generator_density: False
train_generator_as_flow: False
train_generator_on_randn: False
train_generator_g2: False # deprecated
train_generator_packing: False # deprecated
train_generator_adversarially: False
train_discriminator_adversarially: False
train_discriminator_on_randn: True
train_discriminator_on_noise: True
generator_noise_level: 0.1
generator_similarity_penalty: 0
cut_max_prob_training_after: 1000
extra_test_period: 2
sample_after_training: False
extra_test_set_paths: [ '/scratch/mk8347/csd_runs/datasets/blind_test_5_dataset',
                        '/scratch/mk8347/csd_runs/datasets/blind_test_6_dataset',
                        '/scratch/mk8347/csd_runs/datasets/blind_test_targets']
                        #'C:/Users/mikem/Desktop/CSP_runs/datasets/bt_31_dataset',
                        #'C:/Users/mikem/Desktop/CSP_runs/datasets/bt_31_targets',]
d_model_path: null #'C:\Users\mikem\Desktop\CSP_runs\models/cluster/discriminator_150'
g_model_path: null

seeds:
  model: 0
  dataset: 0

# opt - sweep details
wandb:
  sample_reporting_frequency: 1
  experiment_tag: 713_retest_2
  log_figures: True
  sweep_config_file: "sweep_test.yaml"
  sweep: False
  sweep_id: null
  sweep_num_runs: 50

# batching & convergence
grow_batch_size: True
min_batch_size: 10
max_batch_size: 1000
batch_growth_increment: 0.05
max_epochs: 10000 # 0 epochs takes us straight to evaluation mode
history: 1000
gradient_norm_clip: 1

# dataset curation
target: density # 'density' or 'packing' or 'volume'
dataset_length: 1000000
feature_richness: full # full or minimal
max_crystal_temperature: 1000
min_crystal_temperature: -100
max_num_atoms: 100
min_num_atoms: 4 # target XVI has only 9 heavy atoms
max_z_value: 18
min_z_value: 0
max_z_prime: 1
min_z_prime: 1
max_packing_coefficient: 0.85
min_packing_coefficient: 0.55
include_organic: True
include_organometallic: True
max_atomic_number: 100
exclude_missing_r_factor: False
exclude_disordered_crystals: True
exclude_polymorphs: True
exclude_nonstandard_settings: True
exclude_crystal_systems: null #['hexagonal','trigonal','rhombohedral']
exclude_blind_test_targets: True
include_sgs: null #["P-1", "P21/c", "P212121", "C2/c", "Pbca", "P21"]
include_pgs: null #[222,-1,2/m] #[222, -1, 2/m, 2, mm2, mmm, m]
generate_sgs: null #'P2' #'P21/c' # can only do one at a time right now
supercell_size: 1 # 1 = 3x3x3, 2 = 5x5x5 etc. note 1 is too small for small molecules or P1 cells

# https://www.ruppweb.org/Xray/tutorial/enantio.htm non enantiogenic groups

# discriminator optimizer and model
discriminator:
  optimizer: "adamw"
  learning_rate: 0.0001
  max_lr: 0.001
  lr_schedule: True
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.001
  convergence_eps: 0.00001
  training_period: 1 # how often to train the discriminator
  positional_noise: 0 # scaling for the randn noise added to all atom positions

  graph_model: mike
  crystal_convolution_type: 2 # 1 - counts inter and intramolecular the same, 2 - separates intermolecular
  graph_convolution_layers: 4
  graph_filters: 128
  atom_embedding_size: 256
  graph_norm: 'graph layer'
  num_spherical: 6
  num_radial: 36
  graph_convolution_cutoff: 6 # vdw direct force approx 6 angstrom
  max_num_neighbors: 100
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 1 # mikenet self attention mode only - must evenly divide graph filters
  graph_convolution: 'TransformerConv' # 'full message passing' or schnet or 'self attention'
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False #
  pooling: combo

  num_fc_layers: 4
  fc_depth: 256
  activation: leaky relu
  fc_dropout_probability: 0.1
  fc_norm_mode: layer

# generator optimizer and model
generator:
  optimizer: adamw
  learning_rate: 0.00001
  max_lr: 0.0001
  lr_schedule: True
  beta1: 0.9 #0.9
  beta2: 0.999 #0.999
  weight_decay: 0.001
  convergence_eps: 0.00001
  positional_noise: 0 # scaling for the randn noise added to all atom positions

  model_type: nf # mlp or nf
  graph_model: mike
  graph_convolution_layers: 1
  graph_filters: 32
  atom_embedding_size: 32
  graph_norm: null
  num_spherical: 6
  num_radial: 12
  graph_convolution_cutoff: 5
  max_num_neighbors: 32
  radial_function: 'bessel' # mikenet only
  num_attention_heads: 4 # mikenet self attention mode only - must evenly divide graph filters
  graph_convolution: 'self attention' # self attention, schnet, or full message passing
  add_spherical_basis: False # mikenet only
  add_torsional_basis: False
  pooling: combo

  conditioner_num_fc_layers: 1
  conditioner_fc_depth: 32
  conditioner_activation: leaky relu
  conditioner_fc_dropout_probability: 0
  conditioner_fc_norm_mode: null

  num_fc_layers: 1
  fc_depth: 32
  activation: leaky relu
  fc_dropout_probability: 0
  fc_norm_mode: null

  num_samples: 1000
  prior: multivariate normal
  conditional_modelling: True # false will likely not run at all
  conditioning_mode: graph model # molecule features or graph model

  num_flow_layers: 1
  flow_depth: 16
  flow_basis_fns: 8
  flow_type: nsf_cl
